...

diff --git a/bin/bashrc b/bin/bashrc
--- a/bin/bashrc
+++ b/bin/bashrc
@@ -60,17 +60,22 @@ function c() {
   if [ "$1" == "w" ]; then cd *.wiki
   elif [ "$1" == "t" ]; then cd target
   elif [ "$1" == "D" ]; then cd Debug
-  elif [ "$1" == "tr" ]; then cd ~/tbw-ws/ResourceTree
-  elif [ "$1" == "ts" ]; then cd ~/tbw-ws/RESTserver
-  elif [ "$1" == "tt" ]; then cd ~/tbw-ws/FinesseTIplatform
-  elif [ "$1" == "tu" ]; then cd ~/tbw-ws/FinesseUtils
+  elif [ "$1" == "tj" ]; then cd ~/tbw/workspace/jansson
+  elif [ "$1" == "tr" ]; then cd ~/tbw/workspace/ResourceTree
+  elif [ "$1" == "troo" ]; then cd ~/tbw/workspace/rootil
+  elif [ "$1" == "tw" ]; then cd ~/tbw/workspace/RESTserver
+  elif [ "$1" == "tc" ]; then cd ~/tbw/workspace/Configurations
+  elif [ "$1" == "th" ]; then cd ~/tbw/workspace/HouseKeeper
+  elif [ "$1" == "tt" ]; then cd ~/tbw/workspace/FinesseTest
+  elif [ "$1" == "tti" ]; then cd ~/tbw/workspace/FinesseTIplatform
+  elif [ "$1" == "tu" ]; then cd ~/tbw/workspace/FinesseUtils
   elif [ "$1" == "3d" ]; then cd ~/RepRap/Printrun
   elif [ "$1" == "tom" ]; then cd /opt/local/share/tomcat
   elif [ "$1" == "sea" ]; then cd ~/dev
   elif [ "$1" == "fin" ]; then cd ~/finesse
   elif [ "$1" == "tbw" ]; then cd ~/finesse/tbw/workspace
   elif [ "$1" == "tbwd" ]; then cd ~/finesse/tbw-dev/workspace
-  elif [ "$1" == "tw" ]; then cd ~/finesse/tbw.wiki
+  elif [ "$1" == "tbww" ]; then cd ~/finesse/tbw.wiki
   elif [ -e ~/dev/FireSight ]; then cd ~/dev
   elif [ -e ~/github ]; then cd ~/github
   else cd ~
@@ -87,6 +92,8 @@ function c() {
   elif [ "$1" == "fpd" ]; then cd ~/dev/FPD-LooseCanon
   elif [ "$1" == "io" ]; then cd firepick1.github.io
   elif [ "$1" == "html" ]; then cd FireREST/www/html
+  elif [ "$1" == "lc" ]; then cd FPD-LooseCanon
+  elif [ "$1" == "lcw" ]; then cd FPD-LooseCanon.wiki
   elif [ "$1" == "mote" ] || [ "$1" == "m" ]; then cd FireMote
   elif [ "$1" == "o" ]; then cd openpnp/gui
   elif [ "$1" == "p" ]; then cd ~/pixel
@@ -94,9 +101,11 @@ function c() {
   elif [ "$1" == "pick" ]; then cd firepick
   elif [ "$1" == "pixel" ]; then cd ~/pixel
   elif [ "$1" == "pix" ]; then cd ~/pixel
+  elif [ "$1" == "ph" ]; then cd ~/dev/ph5
   elif [ "$1" == "rcl" ]; then cd firerest-client
   elif [ "$1" == "rcm" ]; then cd firerest-cmd
   elif [ "$1" == "r" ]; then cd FireREST
+  elif [ "$1" == "st" ]; then cd FireStep
   elif [ "$1" == "f" ]; then
     if [ -e FireFUSE ]; then cd FireFUSE
     else cd FireREST/FireFUSE
@@ -108,7 +117,7 @@ function c() {
   fi
 }
 
-EXCLUDE="\( -name .metadata -o -name \"*.so\" -o -name bin -o -name ZBar -o -name bootstrap -o -name lib -o -name FireSight -o -name FireFUSE -o -name jansson -o -name jannson -o -name CMakeFiles -o -name opencv -o -name target -o -name node_modules -o -name .git -o -name \"*.class\" -o -name \"*.min.*\" -o -name \"*.o\" \) -prune"
+EXCLUDE="\( -name bower_components -o -name .metadata -o -name \"*.so\" -o -name bin -o -name ZBar -o -name bootstrap -o -name lib -o -name FireSight -o -name FireFUSE -o -name jansson -o -name jannson -o -name CMakeFiles -o -name opencv -o -name target -o -name node_modules -o -name .git -o -name \"*.class\" -o -name \"*.min.*\" -o -name \"*.o\" \) -prune"
 EXCLUDESRC="\( -name \"*.jpg\" -o -name \"*.png\" -o -name \"*.woff\" -o -name \"*.ttf\" \) -prune"
 INCLUDE="\( -name '*.js' -o -name '*.java' -o -name '*.html' -o -name '*.css' -o -name '*.xml' -o -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' -o -name '*.sh' -o -name '*.bat' -o -prune \)"
 
@@ -170,6 +179,36 @@ function seagate {
   ~/seagate/hello
 }
 
+#function bcata {
+	#echo "CMD	: ./build clean all"
+	#./build clean all
+	#rc=$?;
+	#if [ $rc -eq 0 ]; then
+		#echo "CMD	: target/test"
+		#target/test
+	#else
+		#echo "ERROR	: build failed rc:" $rc
+		#return $rc
+	#fi
+#}
+
+function bcati {
+	echo "CMD	: ./build clean all"
+	./build clean all
+	rc=$?;
+	if [ $rc -eq 0 ]; then
+		echo "CMD	: rsync -avz ~/tbw/workspace/Configurations/ ~/ti/Configurations/"
+		rsync -avz ~/tbw/workspace/Configurations/ ~/ti/Configurations/
+		echo "CMD	: rsync -avz ~/ti/ /home/ti/finesse/"
+		rsync -avz ~/ti/ /home/ti/finesse/
+		echo "CMD	: rsync -avz /home/ti/finesse/ root@ti-karl:/home/ti/finesse/"
+		rsync -avz /home/ti/finesse/ root@ti-karl:/home/ti/finesse/
+	else
+		echo "ERROR	: build failed rc:" $rc
+		return $rc
+	fi
+}
+
 alias ec='export CONFIG='
 alias dirty='grep -i dirty /proc/meminfo'
 alias sshjoy='ssh admin@165.225.149.255'
@@ -187,6 +226,7 @@ alias fp80cam='rcp pi@firepick80:/dev/firefuse/sync/cv/1/camera.jpg ~/Downloads 
 alias fpcam='rcp pi@firepick:/dev/firefuse/sync/cv/1/camera.jpg ~/Downloads ; chmod +w ~/Downloads/camera.jpg'
 alias fpdcam='rcp pi@fpd:/dev/firefuse/sync/cv/1/camera.jpg ~/Downloads ; chmod +w ~/Downloads/camera.jpg'
 alias freek='free | grep s.c | grep -Eo "[^ ]*$"'
+alias freem='free -m | grep s.c | grep -Eo "[^ ]*$"'
 alias gcode='echo $1 > /dev/firefuse/cnc/firepick1/gcode.fire'
 alias irc='irssi -c chat.freenode.net -n KarlLew'
 alias bca='./build clean all'
@@ -197,8 +237,20 @@ alias psg='ps -ef | grep -v "grep --color=auto" | grep '
 alias aptinst='dpkg --get-selections | grep -v deinstall | grep'
 alias aptavail='apt-cache search '
 alias bld='./build |& tee build.log'
+alias bpb='./build post-build |& tee build.log'
 alias wintbw='tmux -f ~/pixel/tmux.tbw attach'
 alias win='tmux attach'
+alias tihomefs='sshfs -o nonempty root@ti-home:/home/ti/finesse /home/ti'
+alias tifs='sshfs -o nonempty root@ti-karl:/home/ti/finesse /home/ti/finesse'
+alias fpdfs='sshfs -o nonempty pi@fpd:/home/pi/FireREST ~/fpd'
+alias restdssl='Debug-86/RESTserver -d --ssl -m WebServer/json/FullG4Lite.json ../Configurations/KeyTok.txt'
+alias netex='pushd ~/seagate/Downloads/netExtenderClient; sudo ./netExtender -u klew -p Firepass -d Finesse sslvpn.finesse.com; popd'
+alias restd='Debug-86/RESTserver -d -m WebServer/json/FullG4Lite.json ../Configurations/KeyTok.txt'
+alias rest='Debug-86/RESTserver -m WebServer/json/FullG4Lite.json ../Configurations/KeyTok.txt'
+alias vgnd='valgrind --leak-check=full --show-reachable=yes '
+alias moc1='mocha -w -R min --inline-diffs -g TESTTEST server/firepick/*.js'
+alias moci1='mocha -w -R min --inline-diffs -i -g TESTTEST server/firepick/*.js'
+
 
 export IGNOREEOF=42
 export VISUAL=vim
